---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrd-ha-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xrd-ha-app.labels.standard" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: {{ .Values.haApp.service.exposedPort }}
    targetPort: {{ .Values.haApp.service.targetPort }}
  {{- if .Values.haApp.service.clusterIP }}
  clusterIP: {{ .Values.haApp.service.clusterIP }}
  {{- end }}
