---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xrd-ha-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xrd-ha-app.labels.standard" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- toYaml .Values.global.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.haApp.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.haApp.serviceAccount.annotations | nindent 4 }}
  {{- end }}
