name: tests
on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - 'docs/**'
      - 'commit-check'
  push:
    branches:
      - 'gh-actions'
jobs:
  test:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@master
        with:
          python-version: "3.11"

      - name: Install python packages
        run: |
          pip install -U pip wheel
          pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest tests/ -v --cov ha_app/ --cov-it
